### ISSUE TITLE
windows版本 字体模糊发虚

### ISSUE THREAD

**Issue by necan** [zhuzhuyule/HexoEditor#24]
软件的字体渲染是 Grayscale Anti-Aliasing，低分辨率下很模糊，请支持 Subpixel Anti-Aliasing，就像 Typora 一样清晰。

**Comment by zhuzhuyule** [comment]
是在什么环境以及能否提供截图？

**Comment by necan** [comment]
Windows10，分辨率：1366*768

HexoEditor 字体发虚，100%放大，可以看到是灰度抗锯齿渲染，这种渲染在低分率下，字体是相当模糊的

![hexo_1](https://user-images.githubusercontent.com/25315125/37505736-4491f1cc-2921-11e8-9373-698819228a01.png)

而 Typora 采用的是次像素抗锯齿渲染，这在低分率下也可以看到清晰锐利的字体

![typora](https://user-images.githubusercontent.com/25315125/37505763-6ef36c48-2921-11e8-89a3-07361260b478.png)

**Comment by zhuzhuyule** [comment]
@necan 如果这个是预览效果，可以通过添加样式文件解决。
打开设置:
![](https://i.loli.net/2018/03/27/5aba42ed226f3.png)
添加字体。（可通过 `Ctrl` + `Alt` + `Shift` + `F12`，唤出调试工具辅助）

**Comment by necan** [comment]
@zhuzhuyule 更换css是没有用的，本身并不会更改字体的渲染方式，字体照样是灰度抗锯齿渲染，你没发现，你发的图片上面的标题就是模糊的。

**Comment by necan** [comment]
曾经 Typora 也有这个问题，后来有人反应后，就解决了，[https://github.com/typora/typora-issues/issues/790](https://github.com/typora/typora-issues/issues/790)

**Comment by zhuzhuyule** [comment]
这个我试了，确实是**字体**的问题。
设置：`-webkit-font-smoothing: subpixel-antialiased !important;` 没有任何反应，修改字体会影响显示。

- Typora 使用的字体样式：
```css
{
    font-family: "Open Sans","Clear Sans","Helvetica Neue",Helvetica,Arial,sans-serif;
    font-size: 16px;
}
```
- HexoEditor使用的字体样式：
```css
{
    font-family: "Roboto", "Noto Sans", "Ubuntu", "Helvetica Neue", Helvetica, "Segoe UI", Arial, sans-serif, "Noto Sans CJK SC", "Source Han Sans SC", "Microsoft Yahei";
    font-size: 14px;
}
```

- Typora默认的 `ZoomLevel` 是 `1.2239010857415449`;(可设置连续 +1/-1)
- HexoEditor默认的 `ZoomLevel` 是 `0`;(默认且不可设置)

@necan 感谢提出的问题以及查看到的优化建议。以后将会做显示上的优化。谢谢。
